apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: vehicle-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "1212"
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_NAME
              value: "exploresl"
